### ISSUE TITLE
Missing file aux_labels.txt not in data folder or cbr-rnn-repo-files

### ISSUE THREAD

**Issue by nathimel** [wtimkey/cue-based-retrieval-rnn#1]
Hello, 

After downloading the files from https://drive.google.com/drive/folders/1BlmQGuX_RP8hyveC1b2cXaBx6T4GyKtT, the following error occurs in the 3rd cell of the Analysis notebook:

`FileNotFoundError: [Errno 2] No such file or directory: './data/aux_labels.txt'`

Where might I look for this file?

**Comment by wtimkey** [comment]
Looks like I renamed the file but forgot to change it in the code. Try either renaming the file `aux_vocab.txt` to `aux_labels.txt`, or change that line of code to `aux_vocab.txt`.

**Comment by nathimel** [comment]
Got it, that worked, thanks!
